//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHQ_Cheques_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHQ_Cheques_Master()
        {
            this.CHQ_ChequeClearances_Details = new HashSet<CHQ_ChequeClearances_Details>();
            this.CHQ_ChequeDeposits_Details = new HashSet<CHQ_ChequeDeposits_Details>();
            this.CHQ_ChequeReturns_Details = new HashSet<CHQ_ChequeReturns_Details>();
            this.CHQ_ChequeCancellations_Details = new HashSet<CHQ_ChequeCancellations_Details>();
        }
    
        public decimal Cheque_ID { get; set; }
        public Nullable<decimal> Student_ID { get; set; }
        public Nullable<short> Section_ID { get; set; }
        public Nullable<System.DateTimeOffset> EnteredOn { get; set; }
        public Nullable<decimal> EnteredBy { get; set; }
        public Nullable<decimal> Login_ID { get; set; }
        public Nullable<System.DateTime> InwardDate { get; set; }
        public string ChequeNo { get; set; }
        public string Bank { get; set; }
        public Nullable<decimal> ChqAmount { get; set; }
        public string Remarks { get; set; }
        public Nullable<byte> ChqStatus_ID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHQ_ChequeClearances_Details> CHQ_ChequeClearances_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHQ_ChequeDeposits_Details> CHQ_ChequeDeposits_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHQ_ChequeReturns_Details> CHQ_ChequeReturns_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHQ_ChequeCancellations_Details> CHQ_ChequeCancellations_Details { get; set; }
        public virtual CHQ_ChequeStatus_Lookup CHQ_ChequeStatus_Lookup { get; set; }
    }
}
