//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_UserLogin_Details
    {
        public decimal Login_ID { get; set; }
        public decimal User_ID { get; set; }
        public System.DateTimeOffset LoginTime { get; set; }
        public Nullable<System.DateTimeOffset> LogoutTime { get; set; }
        public string HostName { get; set; }
    }
}
