//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_UserCredentials_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GEN_UserCredentials_Master()
        {
            this.GEN_UserLogin_Details = new HashSet<GEN_UserLogin_Details>();
        }
    
        public decimal User_ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public short SystemRole_ID { get; set; }
        public System.DateTimeOffset EnteredOn { get; set; }
        public bool IsActive { get; set; }
        public System.DateTimeOffset LastModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_UserLogin_Details> GEN_UserLogin_Details { get; set; }
    }
}
