//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUD_DetainingOrPromotions_Details
    {
        public decimal ID { get; set; }
        public decimal Student_ID { get; set; }
        public decimal LastAcadDetail_ID { get; set; }
        public decimal CurrentAcadDetail_ID { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public decimal EnteredBy { get; set; }
        public decimal Login_ID { get; set; }
    }
}
