//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUD_Student_TC
    {
        public decimal StudentTC_ID { get; set; }
        public string RegNo { get; set; }
        public decimal Student_ID { get; set; }
        public decimal IssuedBy_ID { get; set; }
        public System.DateTimeOffset IssuedOn { get; set; }
        public decimal Login_ID { get; set; }
    }
}
